### ISSUE TITLE
SRS Review - Comment #8 - Non-functional requirement

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#10]
- Since you provide a plot as an output, you might consider to add readability conditions as non functional requirements. Having readable colors, fonts, proper size of the characters, proper size of the plot ... are examples of important aspects making a software usable. Since the software is interfacing with a user, a keyboard and a display might be a minimum to consider for an interaction and might be added in user's responsibility as elements to be provided.

I hope my comments are clear enough. If not, do not hesitate to poke me :). Again the comments are only my point of views and I can be wrong. According to me, your SRS document is clear enough to be understood and used at least by me. I might be biased since I am more on the scientific side than on the software engineering side. To complement the feedback, you may consider another student with a deeper software background because I am probably missing some points with my lack of experience.

Anyway, your project looks cool :).

Alex

**Comment by palmerst** [comment]
I have added a non-functional requirement as you suggested in  82cea4f.  Thanks for your comments!
