### ISSUE TITLE
Test Plan:  Address issues from class presentation

### ISSUE THREAD

**Issue by palmerst** [palmerst/cas741_sp#11]
- [x] Add validation responsibilities
- [x] Remove part about code review since I'm not formally doing it
- [x] Add regression testing statement
- [x] Delete R4 in SRS and references to it in test plan
- [x] Move unit tests to unit testing section
- [x] Add integration test for known solution
- [x] Add parallel integration test with Dr. Smith's matlab implementation for Fe(OH)<sub>3</sub>

**Comment by palmerst** [comment]
"Delete R4 in SRS and references to it in test plan" fixed in cff6f3afd231a43327116b20864e4fb9873bbc75 and 940f6a437d72e396d2e6f65c9c75429e66447387

**Comment by smiths** [comment]
Great way to use the issue tracker!
