### ISSUE TITLE
Test Plan: validation (and some spelling/grammar)

### ISSUE THREAD

**Issue by aschaap** [palmerst/cas741_sp#12]
This is a very minor point, but I saw validation was to be carried out via correspondence with Dr. Scott Smith - the PDF says "correspondance". Just out of curiosity, is Dr. Scott Smith in ChemEng, or some external party?

Also, under "Automated Testing", I'd say "integration tests" rather than "integrations tests", but maybe you have a justification for this?

There's also "eachother" under T11.

**Comment by palmerst** [comment]
Thanks -- fixed in  bd44c01

Dr. Scott Smith is actually Dr. Smith's brother -- he is a prof at Wilfred Laurier in the chemistry dept.  :-)
