### ISSUE TITLE
Test Plan: Some (sub)sections have no intro before (sub)subsections

### ISSUE THREAD

**Issue by aschaap** [palmerst/cas741_sp#13]
Another nitpick, some people like text between every pair of headings, perhaps it is worth briefly outlining the section's content? I guess the suggestion applies to other (sub)section headings with no text under them.

**Comment by palmerst** [comment]
Just my opinion, but I feel in technical documents like this that rule should be able to be relaxed.  I prefer leaving it blank if the text is otherwise just restating what the section heading says.
