### ISSUE TITLE
Test Plan: Adding a Table of Symbols

### ISSUE THREAD

**Issue by aschaap** [palmerst/cas741_sp#16]
Since I barely know any chemistry, this might be more of "user" problem (or reader in this case), but perhaps a table with symbols may alleviate some of this - for example, you use a sort of double arrow for chemical equations, perhaps that'd be useful to define?

**Comment by palmerst** [comment]
I actually got rid of the symbols and made the input/output specifications code-based rather than symbolic.  ( bd44c01)
