### ISSUE TITLE
Test Plan: Justification for choice of code coverage metric

### ISSUE THREAD

**Issue by aschaap** [palmerst/cas741_sp#17]
I saw code coverage is your metric of choice. I'm mostly just curious, but are there any particular reasons for this over condition coverage and the like? Perhaps there's less tooling available for this kind of coverage, or is it that the program is very linear in its control flow?

**Comment by palmerst** [comment]
Your assumption is right -- it is simpler to implement via the Python coverage library (I'm not sure if it even does other coverage metrics).  Also, yes, there is not a lot of complicated branching in my implementation, so I'm satisfied with statement coverage.
