### ISSUE TITLE
Test Plan: System Tests vs Integration Tests

### ISSUE THREAD

**Issue by aschaap** [palmerst/cas741_sp#18]
As far as I understand, system tests are integration tests, but integration tests are not necessarily system tests. Tests such as T2 appear to be testing parts of the system rather than the whole, or am I mistaken and will the input be returned to the user? Otherwise, it may be better to move tests like these to Unit Tests. (In my opinion, maybe Dr. @smiths has a different opinion?)

**Comment by palmerst** [comment]
Yes, this was my mistake!  Fixed in  bd44c01
