### ISSUE TITLE
SRS Review - Comment #1 - GS

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#2]
Hi Steven,

Thanks for your clear SRS document. It was pleasant to read.  Mine is way more painful in comparison :). Anyway, I have a few modest comments to provide. All of them are subjective, so do not feel forced to follow them. Please find them below:
- For the goal statements, I think you can mix them both together.  A user wants to "see" the results of the calculation so I don't think the software is usable if only GS1 is satisfied.

**Comment by smiths** [comment]
@slimpotatoes, thank you for your comments on the SRS by @palmerst.  I can tell that you took the review tasks seriously and I can see some great advice/comments for @palmerst.  However, in the future, can you please split your comments into individual issues.  One comment per issue.  This facilitates discussion on any issue and it means that each issue can be closed as it is addressed.  When "issues" are combined into one issue, then the issue can only be closed when the last "issue" has been dealt with.  😄

**Comment by palmerst** [comment]
I have remove GS1, and made the only goal statement that of producing the diagram in 82cea4f
