### ISSUE TITLE
MG: Unlikely Changes Related to Chemical Properties

### ISSUE THREAD

**Issue by GenevaS** [palmerst/cas741_sp#23]
Does periodic table information play a role in your software (e.g. atomic numbers)? If it does, this should probably be listed under unlikely changes.

**Comment by palmerst** [comment]
Currently the inputs are not checked against the periodic table to ensure that chemical symbols are actually elements.  The onus is on the user at this point.

I will list this somewhere as a future plan, since it will be tedious and I don't want to do it for the purposes of the course.  :-)
