### ISSUE TITLE
MG: Input Conversion

### ISSUE THREAD

**Issue by GenevaS** [palmerst/cas741_sp#27]
Is this a different input set than the equation and species data? If so (perhaps the parsed information stored in the chemical system data structure), what is it? If not, what parts of the input are you using here?

**Comment by palmerst** [comment]
The equation and species modules store inputs directly.  All of the equations and species end up being stored in an instance of the Chemical System module.  It is the inputs stored in ChemSys that are being converted.  

The conversion takes the Chemical System and makes equations from the reactions.  It then generates a function which returns a tuple of all of these equations.  This function is then fed to a root solving function (which is the non-linear equation solver).
