### ISSUE TITLE
Review MG comments

### ISSUE THREAD

**Issue by smiths** [palmerst/cas741_sp#29]
I made a comment on your MG for you to review (commit 81cdc00).

**Comment by palmerst** [comment]
MG is finalized in 8e748deeb1570e5e5af9c69b228ba38163b6b9e7


With respect to:  

> 
> What if instead you had a module that stored the calculation output and you could view
> (return/output) the data in whatever form you needed? I think I like your design better, but
> it depends on how complex the data is that you'll be passing around as inputs and outputs
> to your different modules. It looks like none of the modules will have state, except maybe
> M3. It will be easier to judge once your MIS is done. Great initial design. I like the external
> interface idea.

We discussed (at some point) that the data itself isn't very often used -- the diagram itself is what scientists/engineers are usually interested in using.  So I don't think storing the data is necessary.  The solver only takes about a second and it is just a list of lists that is output and passed around.
