### ISSUE TITLE
Review comments on MIS

### ISSUE THREAD

**Issue by smiths** [palmerst/cas741_sp#30]
Comments on the MIS are available at bb9ab20.

**Comment by palmerst** [comment]
Rev 1 of MIS pushed in 411a73045caa62210b3805041f14e17273fdae88

Some comments on your comments:

> 
> Rather than $\mathbb{S}$ etc being strings, would it make more sense to
>   define new types?  The type might be a tuple with fields for molecule and
>   charge.  The molecule in turn could be a sequence  to tuples, where each of
>   these tuples is an element and a number of occurrences.  There are only so
>   many elements to make up the set of elements.  We could use something like
>   this to turn your pseudo type into a real type.  We could go further and
>   capture information about molecules so that the charge could be derived
>   automatically (I think).  I'm not sure exactly what I'm thinking here, but it
>   seems like an opportunity to capture information better than we would just
>   carrying a string around

It makes sense for them to be tuples, but the reason I used strings with attributes for the "pseudotypes" was to avoid the mess and pain of specifying the parsing formally.  If we make them tuples, then there needs to be some way to go from the inputs (which are strings), to the tuples.  So this would lead back to specification of the parsing.  Perhaps there is a way around this, but it's not immediately obvious to me.


> What does this module do that you couldn't get by just having the
>   ChemSys module?  Except for the fact that ChemSys exports an ADT, the syntax
>   of the interfaces are the same?

The External Interface is just supposed to re-export the ChemSys module, and no others.  I'm not sure how to convey this in the MIS, but all of the other modules should not be accessible by the end user.  They should only see the stuff in ChemSys.


> This feels close to a formal model of a species, except for the formula
>   string and the string for E.  Could we also introduce a type for E?  There is
>   a finite set of possibilities for this set.

Yes, E could easily be made to be an enumerated type of all the elements.  I didn't make the change as I don't want to manually enter 118 elements, but Drasil could do this once we have captured the chemistry knowledge!
