### ISSUE TITLE
I don't FileSystem is a variable

### ISSUE THREAD

**Issue by renjiezhang** [palmerst/cas741_sp#32]
@smiths 
In 5.4.2, "FileSystem: The file system of the machine running SpecGen". I don't a system should be a variable or maybe you have multiple file systems and you need to determine one from them.

**Comment by palmerst** [comment]
FileSystem is an environment variable -- it is not a true code variable, but an abstract variable that represents something external to the programming language (in this case the filesystem).  Filesystem here represents the entire filesystem visible to the OS.
