### ISSUE TITLE
The type State is not defined

### ISSUE THREAD

**Issue by renjiezhang** [palmerst/cas741_sp#33]
@smiths 
In 6.3, I saw state: State without the definition of type state.  If it is a enumerator, you need to define it some where.

**Comment by smiths** [comment]
@palmerst is saying that the state variable with the name state has the type State.  The type State is defined above as {s, l, g, aq}.

@renjiezhang, I'm not sure why these questions are addressed to me?  These are @palmerst issues, right?

**Comment by palmerst** [comment]
As @smiths commented, it is defined as an enumerated type in 6.3.1.
