### ISSUE TITLE
SRS Review - Comment #2 - Math symbol

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#4]
I appreciate a lot the mathematical formalism. I just got confused on the symbols ":" and "|" because they both mean the same thing "such that" (if I am correct). From my background, i didn't know that ":" means also "such that" and I just realized that depending on the country, some symbols can have different meaning. Technically, the reader is required to know the mathematical symbolism so it's my fault :). However, two symbols for the same terminology confused me a bit. I don't know what is the typical practice in Canada (or North America in general) but I feel that one symbol should be enough. In your document, I am not entirely sure that the ":" symbol is used for "such that". Sometimes I would read ":" as "in" like "X in set bar(S)" in T3. It might be my knowledge which is not on point regarding sets and terminologies, so please do not consider this comment if I am wrong.

**Comment by palmerst** [comment]
I have added a notation section to the SRS that explains the set based notation in  82cea4f
