### ISSUE TITLE
SRS Review - Comment #3 - Details in equations

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#5]
- Coming back on the mathematical formalism, I don't think that you need to change the equations in the data definitions. I personally see the set of equations in them. You may need to add an subscript R in A_R,B_R,alpha_R and beta_R in DD1 to specify that it is link to reaction R (you can avoid the "with reaction R" statement) and you are good with a few adjustments like that in my opinion. I agree with your comments regarding clarity but if the equations are correct (which seem to be true), it is just a reading argument. Another point, you may need to consider C as a set as well if you want to use bar(K) U bar(M) U C in IM1.

**Comment by palmerst** [comment]
I'm glad you were able to see the sets of equations.  I added spaces/types in my table of symbols to hopefully make it even easier to see in  82cea4f.

Regarding C -- I actually didn't need the charge balance, as it's not actually necessary for solving speciation.  So it has been removed entirely.
