### ISSUE TITLE
SRS Review - Comment #4 - Regrouping some TMs

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#6]
- In your theoretical models, I can see, from both the document and the matrix, that you don't use T1, T4, T5 and T6 in GD, DD or IM. You use them to derive T7 only so, I think you can remove T1, T4, T5 and T6 and a add paragraph below T7 to show how you derived the equation using all the equations in T1, T4, T5 and T6.

**Comment by palmerst** [comment]
The reason I included them was to leave open the possibility of extending the requirements of the program.  By rescinding some of the assumptions, the program can be made more complex to provide a more accurate model.  These TM's will then have associated DD's/IM's.

I am going to leave them as TM's to leave this possibility open.  I don't think having extra information is a problem.  :-)
