### ISSUE TITLE
SRS Review - Comment #6 - Uniqueness of solution in IM1 ?

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#8]
- In IM1, do you expect the solution to be unique ? I would assume yes based on the physical(chemical) aspect but on the mathematical aspect x^2=1 is a non-linear equation with two possible solutions. If you expect a solution and the software find two different ones, can you select one based on physical consideration or are both results valid ? If the uniqueness of the solution is expected and mandatory, it could be considered as a functional requirement.

**Comment by palmerst** [comment]
This is covered in section 2.1, under user responsibilities.  I have left it to the user to ensure that the system they are specifying has a unique speciation solution.
