### ISSUE TITLE
SRS Review - Comment #7 - Requirement

### ISSUE THREAD

**Issue by slimpotatoes** [palmerst/cas741_sp#9]
- In the functional requirements section, I would suggest to add an element in R1, R2 or R3. A non-linear system of equations can exhibit a unique solution under certain conditions depending on the equations.  One of these conditions (in addition to the ones you described) might be linked to the dimensions of the input sets (having the proper number of unknowns and the proper number of equation).  If the dimensions are not respected because the inputs are not proper (one chemical element missing for example), the software might not be able run (or have a set of solutions). So I would suggest to have the dimensions of the input sets checked as a functional requirement. You can go deeper than that the dimensions and add some other conditions that must be satisfied to get a unique solution.

Alex

**Comment by palmerst** [comment]
As mentioned in issue #8, I've placed the onus on the user to ensure that the system will have a unique solution given the data they've entered.
